name: my_test_projeasct
description: A new Flutter project.

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"


environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  http: ^0.12.0
  firebase_messaging: ^5.1.0
  flutter_datetime_picker: ^1.2.5
  cupertino_icons: ^0.1.2
  flutter_local_notifications: ^1.1.5

flutter_icons:
  image_path: "assets\\icon\\res\\mipmap-xxxhdpi\\ic_ACMilan.png" 
  android: true
  ios: true


flutter:
  uses-material-design: true
